### ISSUE TITLE
Failing finding debugbar.js

### ISSUE THREAD

**Issue by jathayde** [julienbourdeau/debugbar#12]
App spins up fine (fixes for #7, et al) but when I render the page, I get this: 

```
10:40:42 web       | Started GET "/_debugbar/assets/script" for ::1 at 2024-02-20 10:40:42 -0500
10:40:42 web       | [Wafris] Redis connection error: File /Users/jathayde/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/debugbar-6e1cb95cb4e1/public/debugbar.js does not exist. Request passed without rules check.
10:40:42 web       |   
10:40:42 web       | ActionController::RoutingError (No route matches [GET] "/assets/script"):
```

Looking in the gem folder, `public` is empty.

**Comment by julienbourdeau** [comment]
Are you using the gem from git or from Rubygem? How did you add it to your project?

If it's from git, indeed the final client is not committed, it's only added when the .gem file is built. You should be able to build it like this:
```
cd client
rm -rf dist
npm install
npm run build
cp dist/assets/debugbar-*.js ../public/debugbar.js
```

I recommend using the latest published version from rubygems.org tho. I'll be publishing many new versions as bug report come in.
