### ISSUE TITLE
Handle ActionCable disabled scenarios

### ISSUE THREAD

**Issue by namiwang** [julienbourdeau/debugbar#19]
So creating the application with `--skip-action-cable` param and breaks debugbar.

1. During routes mounting it requires one `ActionCable` module.
2. It always connects to `/cable` path even if that's not available

**Comment by julienbourdeau** [comment]
Hi @namiwang,

Indeed I didn't handle it well because I was focus on this case: https://github.com/julienbourdeau/debugbar/issues/8

Can you try v0.2.2? It should be fixed 🙏
See https://github.com/julienbourdeau/debugbar/commit/facbe85409b1d89a3d2427274e7c3729c4be16a3

**Comment by namiwang** [comment]
ah sorry should search before opening, I'll close this one then

**Comment by julienbourdeau** [comment]
No worries. It's actually different because you don't have ActionCable installed. 

I was hoping bundler would take care of it since it's declared as a dependency 🤷‍♂️ I'll dig more into dependencies and bundler.
