### ISSUE TITLE
Polling controller returns :verify_authenticity_token not found error

### ISSUE THREAD

**Issue by lockland** [julienbourdeau/debugbar#23]
When I tried to use debugbar on rails  7.1 that doesn't have protect_from_forgery enable an error was returned because the symbol :verify_authenticity_token  is not found, but commenting the line below everything works.

https://github.com/julienbourdeau/debugbar/blob/995c65fb5a5e3f9c9366056e12425c9fcf68e99d/app/controllers/debugbar/polling_controller.rb#L3

**Comment by julienbourdeau** [comment]
I have open a fix in #27 but I haven't tested it yet.

If you can test it, please let me know if it works. Note that I have introduced a breaking change in the latest version: https://debugbar.dev/changelog/

**Comment by lockland** [comment]
The error continues happening as you can see on image below.
Checking on [rails documentation](https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html) I found this statement that could be used to disable CSRF `protect_from_forgery with: :null_session` and testing it here works fine. 
What do you think about using this instead?

![image](https://github.com/julienbourdeau/debugbar/assets/6504339/3a548f5e-84b6-47bc-ba20-8ffcd61c19f6)

**Comment by julienbourdeau** [comment]
Can you confirm you should you tested the git `fix/poll-verify_authenticity_token` branch and not released gem?

In any case, I like what you proposed with `:null_session`, I'll have a look.

**Comment by lockland** [comment]
Yep! I applied your branch's modifications and tested on my environment.

**Comment by julienbourdeau** [comment]
I have released 0.3.1 with the fix. Please let me know if you have the issue again!

**Comment by lockland** [comment]
Now it is working perfectly.
