### ISSUE TITLE
feature request: configuration to have it minimized by default

### ISSUE THREAD

**Issue by andreynering** [julienbourdeau/debugbar#29]
`_debugbarConfigOptions` should have a configuration so the bar is minimized by default, showing that ruby icon to click if I want to open it:

![Screenshot 2024-04-05 at 14 04 35](https://github.com/julienbourdeau/debugbar/assets/7011819/17bb1cab-5c07-4032-9e06-5730432439a5)

**Comment by julienbourdeau** [comment]
Yeah, good idea. I like keeping an eye on it but people could find this useful. I added it here, it will be in the next release: 
 https://github.com/julienbourdeau/debugbar/commit/2046b0540178443d268d2a740a0d73b4039a03dd

**Comment by andreynering** [comment]
Thanks @julienbourdeau!
