### ISSUE TITLE
Difficult to remove debugbar

### ISSUE THREAD

**Issue by obromios** [julienbourdeau/debugbar#30]
I was having trouble with assets management and as part of the process to work out what was happening, I removed the debugbar gem, removed the engine routes.rb, and removed the helpers in the application.html.  I had not made any changes to relating to ActionCable.  Having done this and restarted the server, I keep seeing every ten second or so

`ActionController::RoutingError (No route matches [GET] "/_debugbar/cable"):`

What else do I need to do to stop this happening?

It turned out that debugbar was not the cause of the problem I was having with asset management, so I am reinstalling it, and in future will use the initialiser to disable it if necessary.  But it seems to me desirable for debugbar to be removable without any side-effects.

**Comment by julienbourdeau** [comment]
I assume the frontend was still loading the debugbar, maybe in another tab 🤔 
In this case, as you mentioned using the config would be easier. Overall I agree it should be easy to remove and as centralized as possible. 

```
Debugbar.configure do |config|
  config.enabled = false
end
```

I'll keep it in mind and we'll see if this issue occurs again. Thank you for sharing 🙏

**Comment by obromios** [comment]
I did clear all tabs, but a reboot seems to have cleared it, which I should have tried in the first place. Anyway thank you for your patience.
