### ISSUE TITLE
exception after installation (undefined method `filter')

### ISSUE THREAD

**Issue by edk** [julienbourdeau/debugbar#7]
Rails 7.1.3
Ruby 3.3.0

I added the gem to the `development` and `test` section of my Gemfile.  Added the route and the debugbar_javascript to my application layout.

However, I'm getting the following error:

```
$ rails test
[...]
.rvm/gems/ruby-3.3.0/bundler/gems/debugbar-eb2430db8435/lib/debugbar/subscribers/active_record.rb:38:in `block in sql': undefined method `filter' for class Debugbar::ActiveRecordEventSubscriber (NoMethodError)

            filtered_params = filter(attribute_name, casted_params[i])
                              ^^^^^^
	from .rvm/gems/ruby-3.3.0/bundler/gems/debugbar-eb2430db8435/lib/debugbar/subscribers/active_record.rb:29:in `each'
	from .rvm/gems/ruby-3.3.0/bundler/gems/debugbar-eb2430db8435/lib/debugbar/subscribers/active_record.rb:29:in `each_with_index'
	from .rvm/gems/ruby-3.3.0/bundler/gems/debugbar-eb2430db8435/lib/debugbar/subscribers/active_record.rb:29:in `sql'
```

and I get the same error when trying to process a request from `rails s`

I also tried the tagged version and master from the repo, with the same results as from the rubygems version.

let me know if there's any other information that could be helpful.  Thanks, and interested in trying this out!

**Comment by julienbourdeau** [comment]
Can you try v.0.1.4 please 🙏 

I'm really sorry for this, it was silly to try to fix it quickly instead of removing it in #7.
