### ISSUE TITLE
Server start failure when ActionCable is not loaded

### ISSUE THREAD

**Issue by taylorthurlow** [julienbourdeau/debugbar#8]
I tend to exclude railties that I am not using in a Rails app, so in the case of debugbar I am failing to start due to ActionCable not being defined.

```
/Users/taylor/.anyenv/envs/rbenv/gems/3.2.0/gems/debugbar-0.1.3/config/routes.rb:2:in `block in <main>': uninitialized constant ActionCable (NameError)

  mount ActionCable.server => '/cable'
        ^^^^^^^^^^^
Did you mean?  ActionMailer
```

It does look like debugbar requires ActionCable, which is fine, but it seems worth adding a check and a clear error message about why it failed.

**Comment by julienbourdeau** [comment]
I'm trying to think about a good way to handle this. It should probably be an initializer in `engine.rb`.

I expected that bundler or rails would handle it has I defined ActionCable [as a dependency in the .gemspec](https://github.com/julienbourdeau/debugbar/blob/751ac275265370ea24e07a338de0f75361e78b87/debugbar.gemspec#L34-L34).

I'm hoping to add a polling version in case ActionCable is not available but I wanted to publish a first version before that. Let's how many people interested in the debugbar have removed ActionCable.

**Comment by taylorthurlow** [comment]
> I expected that bundler or rails would handle it has I defined ActionCable [as a dependency in the .gemspec](https://github.com/julienbourdeau/debugbar/blob/751ac275265370ea24e07a338de0f75361e78b87/debugbar.gemspec#L34-L34).

I think this is still the right move - by excluding the require statement for the railtie in my `application.rb`, I'm only avoiding the runtime penalty of actually starting/requiring it, ActionCable is definitely still part of my bundle.

**Comment by julienbourdeau** [comment]
Oh yeah I see 👍

**Comment by diasjorge** [comment]
I work on some apps that don't use actioncable so having some polling option would be great. The demo looks really promising. Thanks for making this awesome tool
